# Generated by Django 3.2.12 on 2022-04-25 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equip',
            unique_together=set(),
        ),
    ]
