# Generated by Django 3.2.12 on 2022-04-25 23:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_alter_equip_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equip',
            unique_together={('user', 'brand')},
        ),
    ]
